<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '确定要删除吗？',
    'Boxes' => '箱',
    'Create' => '创建',
    'Create Box' => '新建箱',
    'Create Employee' => '新建员工',
    'Create Package' => '新建包装盒',
    'Create Product' => '进货',
    'Create Stock' => '新建仓库',
    'Create Type' => '新建类型',
    'Delete' => '删除',
    'Employees' => '员工',
    'ID' => '编号',
    'Name' => '名称',
    'Net Price' => '进货单价',
    'Number' => '编码',
    'Packages' => '包装盒',
    'Price' => '销售单价',
    'Products' => '产品',
    'Specs' => '规格',
    'Rate' => '时薪',
    'Reset' => '重置',
    'Search' => '搜索',
    'Stocks' => '库存',
    'Box ID' => '箱',   
    'Box Name' => '箱',
    'Type ID' => '类型',
    'Type Name' => '类型',
    'Types' => '类型',
    'Update' => '修改',
    'Update {modelClass}: ' => '',
    'Processes' => '过程',
    'Create Process' => '新建过程',
    'Create Spec' => '新建规格',
    'Parent Process Name' => '上级过程',
    'Process Name' => '过程名称',
    'Process Relations' => '过程关系',
    'Create Process Relation' => '新建过程关系',
    'Employee' => '员工',
    'Hours' => '工时',
    'Spec ID' => '规格',
    'Quantity' => '数量',
    'Spec Name' => '规格',
    'Finish' => '完成',
    'Next Product' => '下一个',
    'Employee Name' => '员工',
];
